from dataclasses import dataclass

@dataclass  
class cycle_agg_data:
    id: int
    cycle: int
    setting1: float
    setting2: float
    setting3: float
    s1: float
    s2: float
    s3: float
    s4: float
    s5: float
    s6: float
    s7: float
    s8: float
    s9: float
    s10: float
    s11: float
    s12: float
    s13: float
    s14: float
    s15: float
    s16: float
    s17: float
    s18: float
    s19: float
    s20: float
    s21: float
    a1: float
    a2: float
    a3: float
    a4: float
    a5: float
    a6: float
    a7: float
    a8: float
    a9: float
    a10: float
    a11: float
    a12: float
    a13: float
    a14: float
    a15: float
    a16: float
    a17: float
    a18: float
    a19: float
    a20: float
    a21: float
    sd1: float
    sd2: float
    sd3: float
    sd4: float
    sd5: float
    sd6: float
    sd7: float
    sd8: float
    sd9: float
    sd10: float
    sd11: float
    sd12: float
    sd13: float
    sd14: float
    sd15: float
    sd16: float
    sd17: float
    sd18: float
    sd19: float
    sd20: float
    sd21: float